#pragma once

#include "greis/CustomType/BandDelayCustomType.h"
#include "greis/CustomType/ClkOffsCustomType.h"
#include "greis/CustomType/ESICustomType.h"
#include "greis/CustomType/ExtSpecDataCustomType.h"
#include "greis/CustomType/GPSAlm1CustomType.h"
#include "greis/CustomType/GPSEphemeris1CustomType.h"
#include "greis/CustomType/GpsEphOptDataCustomType.h"
#include "greis/CustomType/GpsEphReqDataCustomType.h"
#include "greis/CustomType/GpsNavData1CustomType.h"
#include "greis/CustomType/GpsRawNavData1CustomType.h"
#include "greis/CustomType/HeaderCustomType.h"
#include "greis/CustomType/IonoParams1CustomType.h"
#include "greis/CustomType/SlotRecCustomType.h"
#include "greis/CustomType/SmoothCustomType.h"
#include "greis/CustomType/SpecDataCustomType.h"
#include "greis/CustomType/SvData0CustomType.h"
#include "greis/CustomType/SvData1CustomType.h"
#include "greis/CustomType/SvData2CustomType.h"
#include "greis/CustomType/SvDelayCustomType.h"
#include "greis/CustomType/UtcOffsCustomType.h"

